#!../support/bin/lua

package.path = "./lib/?.lua;" .. package.path
package.cpath = "../support/lib/?.so;" .. package.cpath

--
---- Use our library autoloading mechanism
----
dofile("lib/lib.lua")


lib.ip.addr.add("1.2.3.4/24", "eth0")

